### ISSUE TITLE
Navigation Guards for admin and courier routes

### ISSUE THREAD

**Issue by IncognitoJam** [campus-bites/campus-bites-vue#50]
Some pages in the app must have restricted access, such as the Admin and Courier dashboards. Once implemented these must only be accessible by users who have the correct permissions. The [user spec](https://docs.google.com/document/d/1X_ueQAeJGx7R6mnOVJ0ndaSYlUJQ8uGGnl2uQqH4e_I/edit#bookmark=id.lhdlj1bwya3l) has a property for a permissions map (with keys `admin` and `courier`).

Create two [Navigation Guard](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-guards)s, one for the admin permission and another for the courier permission, and attach them to the restricted routes.

**Comment by IncognitoJam** [comment]
Admin and auth guards implemented in 87b73acfd917cc68e10ab7a35d0563d97293860c. Courier guard on hold until the courier page has been implemented.

**Comment by nathanial292** [comment]
Bug with the from value. The value is always null regardless of whether the user was on a page previously. Resulting in redirecting to a blank page

**Comment by nathanial292** [comment]
The 'from' value is always null when changing page. Resulting in a redirect to a blank page. In router.js when the beforeEach function is called. Not sure why this is, did this used to work?

**Comment by IncognitoJam** [comment]
> The 'from' value is always null when changing page. Resulting in a redirect to a blank page. In router.js when the beforeEach function is called. Not sure why this is, did this used to work?

`from` is undefined if you access a route by typing the URL into the address bar (you aren't actually nagivating from anywhere else in the app). This works fine when you are clicking a button or anything else with the `to` prop.

**Comment by IncognitoJam** [comment]
The guards don't allow you to access pages when you type the URL though, which isn't really intended. This is because the state hasn't been loaded before the router guard is called. Vuex needs to load the state from local storage sooner.

**Comment by IncognitoJam** [comment]
I will revisit the Vuex state issue in the future.
