### ISSUE TITLE
Prices > £9.99 display incorrectly using the price.js filter.

### ISSUE THREAD

**Issue by alex-woodhouse** [campus-bites/campus-bites-vue#54]
![image](https://user-images.githubusercontent.com/25963284/51078168-3706fe00-16a9-11e9-898e-3727adb2c3c5.png)

Prices greater than £9.99 are displayed incorrectly in the basket on the menu page. I believe the logic error to be contained within filters/price.js

**Comment by alex-woodhouse** [comment]
![image](https://user-images.githubusercontent.com/25963284/51078168-3706fe00-16a9-11e9-898e-3727adb2c3c5.png)

Prices greater than £9.99 are displayed incorrectly. I believe the logic error to be contained within filters/price.js

**Comment by IncognitoJam** [comment]
Fixed in the meeting!
