### ISSUE TITLE
Fix Basket component position and size

### ISSUE THREAD

**Issue by IncognitoJam** [campus-bites/campus-bites-vue#61]
If the screen width is too small, the basket component does not always move out of the way of the content so the text will not fit.

![image](https://user-images.githubusercontent.com/4038174/51490188-65b85f00-1da2-11e9-9d83-4cfa1bba0e14.png)

The basket should move to a different location on the page where there is more space when this happens. Perhaps use a [Bottom sheet](https://vuetifyjs.com/en/components/bottom-sheets).

**Comment by IncognitoJam** [comment]
Fixed in 69188e8132c2bacd90c98f955aff4be109931fb3.

**Comment by nathanial292** [comment]
Did you fix this? I'll have a look later because it's still squished. Perhaps give it more vflex grid space on medium - smaller screens

**Comment by IncognitoJam** [comment]
Fixed again in 2b7608980a543c3623c2f82f5665fc433bdd7abd.
